- 00-intro/intro.md
- 95-glossary/glossary.md
- 95-glossary/glossary.tex
Adding dummy overview to see how it all works.
> Add Overview

- 00-intro/intro.md
Use "Neo Green" color from [Neo Brand Book](https://neo3.azureedge.net/images/presskit/Neo%20Brand%20Book_v1.0_20191017.pdf)
> Fix titlepage line color

- templates/apiv2-package.tmpl
SessionToken.Body message was not included in Spec before.
> Fix SessionToken.Body display

- 20-api-v2/netmap.md
- 20-api-v2/object.md
- 20-api-v2/tombstone.md
Update Spec to match NeoFS API v2.4.0
> Update Spec to match NeoFS API v2.4.0

- 01-arch/01-netmap.md
- 01-arch/02-policy.md
- 95-glossary/glossary.md
Some sections are skipped to be filled later.
Comments are welcome.
Close #8 .
> Describe netmap and storage policy

- 00-intro/intro.md
- 01-arch/00-overview.md
- 01-arch/01-netmap.md
- 01-arch/02-policy.md
- 01-arch/04-object_split.md
- 02-blockchain/01-governance.md
- 95-glossary/glossary.md
- 95-glossary/glossary.tex
- README.md
Moving to single line paragraphs, as the filled paragraphs are harder to merge via GitHub review interface and hard to have the same filling with different text editors.
> Move to single line paragraph style.

- 00-intro/intro.md
- 01-arch/00-overview.md
- 01-arch/04-object_split.md
- 02-blockchain/01-governance.md
- 02-blockchain/11-mainnet.md
- 95-glossary/glossary.md
- 95-glossary/glossary.tex
Some suggested copy changes for each current section, excluding the API.
> Updates to spec copy

- 01-arch/07-reputation.md
- 07-reputation/00-intro.md
- 07-reputation/01-configuration.md
- 07-reputation/02-managers.md
- 07-reputation/03-localtrust.md
- 07-reputation/04-globaltrust.md
- 95-glossary/glossary.md
- 95-glossary/glossary.tex
> Add reputation description

- 06-blockchain/00-intro.md
- 95-glossary/glossary.tex
> blockchain: Add intro section

- 95-glossary/glossary.tex
Ending dots are added by default, removing them.
> Remove ending dots.

- 03-storage/10-expiration.md
Signed-off-by: anastasia prasolova <anastasia@nspcc.ru>
> expiration date for objects

- 06-blockchain/03-alphabet.md
- 06-blockchain/03-audit.md
- 06-blockchain/03-balance.md
- 06-blockchain/03-container.md
- 06-blockchain/03-neofs.md
- 06-blockchain/03-neofsid.md
- 06-blockchain/03-netmap.md
- 06-blockchain/03-processing.md
- 06-blockchain/03-proxy.md
- 06-blockchain/03-reputation.md
- 06-blockchain/03-subnet.md
- 20-api-v2/accounting.md
- 20-api-v2/acl.md
- 20-api-v2/container.md
- 20-api-v2/netmap.md
- 20-api-v2/object.md
- 20-api-v2/refs.md
- 20-api-v2/reputation.md
- 20-api-v2/session.md
- 20-api-v2/status.md
- 20-api-v2/subnet.md
Update API and Contracts documentation to fix latest versions
> Update API and Contracts

- 03-storage/20-notification.md
> storage: Describe general rules of notifications

- Makefile
- neofs-cdn.yaml
Signed-off-by: anastasia prasolova <anastasia@nspcc.ru>
> [nspcc-dev/nspcc-infra#497]: added neofs-cdn.yaml

- 01-arch/07-acl.md
Signed-off-by: anastasia prasolova <anastasia@nspcc.ru>
> ACL clarification

- 01-arch/06-containers.md
- 01-arch/07-acl.md
Signed-off-by: anastasia prasolova <anastasia@nspcc.ru>
> Clarified ACL for IR and SN

- 04-gates/00-gates.md
Signed-off-by: Denis Kirillov <denis@nspcc.ru>
> [#80] Add new line to fix list formatting

- 04-gates/00-gates.md
Signed-off-by: Denis Kirillov <denis@nspcc.ru>
> [#81] Fix typo in secret_access_key

- 01-arch/07-acl.md
Signed-off-by: Evgenii Stratonikov <evgeniy@nspcc.ru>
> arch/acl: replace ALC with ACL

- .github/workflows/dco.yml
From a miraculous org-wide .github repository.
> workflows: shiny new DCO check

- .github/workflows/neofs.yml
Signed-off-by: Mikhail Petrov <mike@nspcc.ru>
> fix: NeoFS upload github action

- .github/workflows/neofs.yml
> every step must define a `uses` or `run` key
> .github: fix NeoFS upload workflow (again)

- .github/workflows/neofs.yml
https://github.com/nspcc-dev/gh-push-to-neofs/pull/29
> workflows: upgrade gh-push-to-neofs to fix upload issue
